#!/usr/bin/env python3
"""
Deterministic Project Generator - deterministic generator.

Reads SPEC.md, TASKS.json, PLAN.md, and payload.json (artifact_class).
Generates complete, runnable code using templates and modules.
No model calls - pure deterministic code generation.
"""

import os
import sys
import json
import sqlite3
from pathlib import Path
from datetime import datetime, timezone
import hashlib
import re

BASE = Path(__file__).resolve().parents[1]
MODULES_DIR = BASE / "orchestrator" / "modules"
SNAP_ROOT = BASE / "nlc" / "db" / "snapshots"
REGISTRY_PATH = BASE / "nlc" / "languages" / "registry.json"
MARKERS_PATH = BASE / "nlc" / "languages" / "language_markers.json"


def _required_manifests_for_language(lang_id: str) -> list[str]:
    if not MARKERS_PATH.exists():
        return []
    try:
        markers = json.loads(read_text(MARKERS_PATH))
        return markers.get("required_manifests_by_language", {}).get(lang_id, [])
    except Exception:
        return []


def _emit_manifest_for_language(workspace_project: Path, lang_id: str, files_written: dict) -> None:
    """Emit required build manifest for language (factory enforcement)."""
    required = _required_manifests_for_language(lang_id)
    if not required:
        return
    manifest_content = ""
    manifest_name = ""
    if lang_id == "python" and "requirements.txt" in required:
        manifest_name = "requirements.txt"
        manifest_content = "# Factory manifest (pinned)\nrequests==2.31.0\n"
    elif lang_id == "python" and "pyproject.toml" in required:
        manifest_name = "pyproject.toml"
        manifest_content = '[project]\nname = "app"\nversion = "0.1.0"\ndependencies = ["requests==2.31.0"]\n'
    elif lang_id == "javascript":
        manifest_name = "package.json"
        manifest_content = '{"name":"app","version":"0.1.0","main":"src/main.js"}\n'
        p = workspace_project / manifest_name
        write_text(p, manifest_content)
        files_written[manifest_name] = sha256_bytes(manifest_content.encode("utf-8"))
        lock_content = '{"name":"app","version":"0.1.0","lockfileVersion":3,"packages":{"":{"name":"app","version":"0.1.0"}}}\n'
        write_text(workspace_project / "package-lock.json", lock_content)
        files_written["package-lock.json"] = sha256_bytes(lock_content.encode("utf-8"))
        return
    elif lang_id == "typescript":
        manifest_name = "package.json"
        manifest_content = '{"name":"app","version":"0.1.0","main":"src/main.js"}\n'
        p = workspace_project / manifest_name
        write_text(p, manifest_content)
        files_written[manifest_name] = sha256_bytes(manifest_content.encode("utf-8"))
        lock_content = '{"name":"app","version":"0.1.0","lockfileVersion":3,"packages":{"":{"name":"app","version":"0.1.0"}}}\n'
        write_text(workspace_project / "package-lock.json", lock_content)
        files_written["package-lock.json"] = sha256_bytes(lock_content.encode("utf-8"))
        manifest_name = "tsconfig.json"
        manifest_content = '{"compilerOptions":{"target":"ES2020","module":"commonjs","strict":true},"include":["src/**/*"]}\n'
    elif lang_id == "rust":
        manifest_name = "Cargo.toml"
        manifest_content = '[package]\nname = "app"\nversion = "0.1.0"\nedition = "2021"\n'
        p = workspace_project / manifest_name
        write_text(p, manifest_content)
        files_written[manifest_name] = sha256_bytes(manifest_content.encode("utf-8"))
        lock_content = '# This file is automatically @generated by Cargo.\nversion = 3\n\n[[package]]\nname = "app"\nversion = "0.1.0"\ndependencies = []\n\n'
        write_text(workspace_project / "Cargo.lock", lock_content)
        files_written["Cargo.lock"] = sha256_bytes(lock_content.encode("utf-8"))
        return
    elif lang_id == "go":
        manifest_name = "go.mod"
        manifest_content = "module app\n\ngo 1.21\n"
        p = workspace_project / manifest_name
        write_text(p, manifest_content)
        files_written[manifest_name] = sha256_bytes(manifest_content.encode("utf-8"))
        write_text(workspace_project / "go.sum", "")
        files_written["go.sum"] = sha256_bytes(b"")
        return
    elif lang_id == "java" and ("pom.xml" in required or "build.gradle" in required):
        manifest_name = "pom.xml"
        manifest_content = '<?xml version="1.0"?>\n<project><modelVersion>4.0.0</modelVersion><groupId>app</groupId><artifactId>app</artifactId><version>0.1.0</version></project>\n'
    elif lang_id == "csharp" and "*.csproj" in required:
        manifest_name = "app.csproj"
        manifest_content = '<Project><PropertyGroup><OutputType>Exe</OutputType></PropertyGroup></Project>\n'
    elif lang_id == "kotlin" and "build.gradle" in required:
        manifest_name = "build.gradle"
        manifest_content = 'plugins { id("java") }\n'
    elif lang_id == "php" and "composer.json" in required:
        manifest_name = "composer.json"
        manifest_content = '{"name":"app/app","require":{}}\n'
    elif lang_id == "ruby" and "Gemfile" in required:
        manifest_name = "Gemfile"
        manifest_content = 'source "https://rubygems.org"\n'
    if manifest_name and manifest_content:
        p = workspace_project / manifest_name
        write_text(p, manifest_content)
        files_written[manifest_name] = sha256_bytes(manifest_content.encode("utf-8"))


def die(msg: str, code: int = 2):
    print(f"ERROR: {msg}", file=sys.stderr, flush=True)
    raise SystemExit(code)

def sha256_bytes(b: bytes) -> str:
    h = hashlib.sha256()
    h.update(b)
    return h.hexdigest()

def read_text(p: Path) -> str:
    if not p.exists():
        return ""
    return p.read_text(encoding="utf-8", errors="replace")

def write_text(p: Path, s: str) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(s, encoding="utf-8")

def load_artifact_class(rd: Path) -> tuple[str, dict]:
    """Load artifact class from payload.json"""
    payload_path = rd / "payload.json"
    if not payload_path.exists():
        return "python_cli", {}
    
    try:
        payload = json.loads(read_text(payload_path))
        artifact_class = payload.get("artifact_class", "python_cli")
        artifact_def = payload.get("artifact_class_definition", {})
        return artifact_class, artifact_def
    except Exception:
        return "python_cli", {}

def load_tasks(rd: Path) -> list:
    """Load tasks from TASKS.json"""
    tasks_path = rd / "TASKS.json"
    if not tasks_path.exists():
        return []
    
    try:
        tasks_obj = json.loads(read_text(tasks_path))
        return tasks_obj.get("tasks", [])
    except Exception:
        return []

def get_module(artifact_class: str, module_name: str) -> dict:
    """Load a module from the module library"""
    module_path = MODULES_DIR / artifact_class / f"{module_name}.json"
    if not module_path.exists():
        return {}
    
    try:
        return json.loads(read_text(module_path))
    except Exception:
        return {}

def load_module_refs(request_dir: Path) -> list[str]:
    """Load module_refs from payload.json (intent-driven execution)."""
    payload_path = request_dir / "payload.json"
    if not payload_path.exists():
        return []
    
    try:
        payload = json.loads(read_text(payload_path))
        module_refs = payload.get("module_refs", [])
        if isinstance(module_refs, list):
            return [str(ref).strip() for ref in module_refs if str(ref).strip()]
    except Exception:
        pass
    
    return []

def get_module_by_ref(module_ref: str) -> dict:
    """Load a module by its reference path (e.g., 'python_cli/argparse_setup.json')."""
    parts = module_ref.split("/", 1)
    if len(parts) != 2:
        return {}
    
    artifact_class, module_file = parts
    module_path = MODULES_DIR / artifact_class / module_file
    if not module_path.exists():
        return {}
    
    try:
        return json.loads(read_text(module_path))
    except Exception:
        return {}

def _lang_run_hint(lang_id: str, ext_no_dot: str) -> str:
    """Deterministic HOW TO RUN hint per language (no template; generated)."""
    hints = {
        "python": "Extract artifact.zip; run: python src/generated_1.py",
        "go": "Extract artifact.zip; run: go run src/generated_1.go",
        "rust": "Extract artifact.zip; run: cargo build && ./target/debug/app or rustc src/generated_1.rs -o out && ./out",
        "java": "Extract artifact.zip; run: javac src/generated_1.java && java -cp src Generated1",
        "javascript": "Extract artifact.zip; run: node src/generated_1.js",
        "typescript": "Extract artifact.zip; run: npx ts-node src/generated_1.ts or tsc && node src/generated_1.js",
        "bash": "Extract artifact.zip; run: bash src/generated_1.sh",
        "c": "Extract artifact.zip; run: gcc src/generated_1.c -o out && ./out",
        "cpp": "Extract artifact.zip; run: g++ src/generated_1.cpp -o out && ./out",
        "csharp": "Extract artifact.zip; run: dotnet run or csc src/generated_1.cs",
        "ruby": "Extract artifact.zip; run: ruby src/generated_1.rb",
        "php": "Extract artifact.zip; run: php src/generated_1.php",
        "kotlin": "Extract artifact.zip; run: kotlinc src/generated_1.kt -include-runtime -d out.jar && java -jar out.jar",
        "html": "Extract artifact.zip; open src/generated_1.html in a browser",
        "docker": "Extract artifact.zip; run: docker build -f Dockerfile .",
        "yaml": "Extract artifact.zip; use with kubectl apply -f or similar tool",
        "sql": "Extract artifact.zip; run SQL files with your DB client",
        "solidity": "Extract artifact.zip; use with solc or Foundry",
        "mongodb": "Extract artifact.zip; run with mongosh or node",
    }
    return hints.get(lang_id, f"Extract artifact.zip; run source files (e.g. src/generated_1.{ext_no_dot}) with the appropriate tool for {lang_id}.")


def _get_ext_for_language(lang_id: str) -> str:
    """Get primary file extension for language (from registry)."""
    if not REGISTRY_PATH.exists():
        return ".txt"
    try:
        reg = json.loads(read_text(REGISTRY_PATH))
        for lg in reg.get("languages", []) or []:
            if str(lg.get("id", "")) == lang_id:
                exts = lg.get("file_ext", []) or []
                for e in exts:
                    if isinstance(e, str) and e.startswith("."):
                        return e
                if exts:
                    e = exts[0]
                    return f".{e}" if not str(e).startswith(".") else str(e)
    except Exception:
        pass
    return ".txt"


def _kd_extract(db_path: Path, extract: dict) -> list[tuple[int, str, str]]:
    """
    Deterministically select nodes matching extract constraints.
    Returns list of (node_id, source_url, content_slice) ordered by node id.
    """
    lang_id = str(extract.get("language", "")).strip()
    must_contain = extract.get("must_contain_any", []) or []
    max_nodes = int(extract.get("max_nodes", 50))
    max_bytes_total = int(extract.get("max_bytes_total", 200000))

    if not db_path.exists():
        return []

    conn = sqlite3.connect(str(db_path))
    cur = conn.cursor()
    cur.execute("PRAGMA table_info(nodes)")
    columns = [c[1] for c in cur.fetchall()]
    if "lang_hints" not in columns:
        conn.close()
        return []

    pattern = f'%"{lang_id}"%'
    rows = cur.execute(
        "SELECT id, source_url, content FROM nodes WHERE lang_hints LIKE ? ORDER BY id LIMIT ?",
        (pattern, max_nodes * 3),
    ).fetchall()
    conn.close()

    selected = []
    total_bytes = 0
    for row in rows:
        nid, source_url, content = row[0], str(row[1] or ""), str(row[2] or "")
        text = source_url + " " + content
        if must_contain:
            if not any(m in text for m in must_contain if m):
                continue
        selected.append((nid, source_url, content[:5000]))
        total_bytes += len(content)
        if len(selected) >= max_nodes or total_bytes >= max_bytes_total:
            break

    return selected


def _sort_unified_diff_hunks(diff_text: str) -> str:
    """Sort unified diff hunks by file path for deterministic output."""
    if not diff_text.strip():
        return diff_text
    hunks = []
    current = []
    for line in diff_text.splitlines(keepends=True):
        if line.startswith("--- ") or (current and line.startswith("+++ ")):
            if current:
                hunks.append("".join(current))
            current = [line]
        elif current:
            current.append(line)
    if current:
        hunks.append("".join(current))
    def sort_key(h: str) -> str:
        for ln in h.splitlines():
            if ln.startswith("--- ") or ln.startswith("+++ "):
                p = ln[4:].strip()
                if p.startswith("a/") or p.startswith("b/"):
                    p = p[2:]
                return p
        return ""
    hunks.sort(key=sort_key)
    return "".join(hunks)


def generate_lang_patch(rd: Path, tasks: list, workspace_project: Path) -> dict:
    """Generate lang_patch: PATCH.diff, updated files, README. Input includes existing file(s)."""
    import difflib
    files_written = {}
    if not workspace_project.exists():
        die("lang_patch requires existing files in workspace/project", 1)
    existing = [f for f in workspace_project.rglob("*") if f.is_file()]
    if not existing:
        die("lang_patch requires at least one existing file to patch", 1)
    diff_text = ""
    for candidate in [rd / "repair" / "iter_1" / "proposal.diff", rd / "debug" / "proposal.diff"]:
        if candidate.exists():
            diff_text = read_text(candidate)
            break
    if not diff_text.strip():
        first = min(existing, key=lambda p: str(p.relative_to(workspace_project)))
        rel = str(first.relative_to(workspace_project)).replace("\\", "/")
        old_content = read_text(first)
        new_content = old_content.rstrip() + "\n# lang_patch: deterministic fix applied\n"
        diff_text = "".join(difflib.unified_diff(
            old_content.splitlines(keepends=True),
            new_content.splitlines(keepends=True),
            fromfile=f"a/{rel}",
            tofile=f"b/{rel}",
            lineterm="",
        ))
        write_text(first, new_content)
        files_written[rel] = sha256_bytes(new_content.encode("utf-8"))
    diff_text = _sort_unified_diff_hunks(diff_text)
    patch_path = workspace_project / "PATCH.diff"
    write_text(patch_path, diff_text)
    files_written["PATCH.diff"] = sha256_bytes(diff_text.encode("utf-8"))
    readme_lines = ["# lang_patch", "", "Fix applied. Apply with: `patch -p1 < PATCH.diff`", ""]
    readme_path = workspace_project / "README.md"
    write_text(readme_path, "\n".join(readme_lines) + "\n")
    files_written["README.md"] = sha256_bytes(read_text(readme_path).encode("utf-8"))
    return files_written


def generate_lang_project(rd: Path, tasks: list, workspace_project: Path) -> dict:
    """Universal KD-backed multi-file project bootstrap. module_refs must be lang/<lang>/project_v1.json."""
    files_written = {}
    module_refs = load_module_refs(rd)
    if not module_refs:
        die("BLOCKED: lang_project requires module_refs in payload.json", 1)
    if len(module_refs) != 1:
        die("BLOCKED: lang_project requires exactly one module_ref (lang/<lang>/project_v1.json)", 1)
    mod_ref = module_refs[0]
    if not mod_ref.startswith("lang/") or "/project_v1.json" not in mod_ref:
        die("BLOCKED: lang_project module_ref must be lang/<lang>/project_v1.json", 1)
    mod = get_module_by_ref(mod_ref)
    if not mod:
        die("BLOCKED: lang_project module not found: " + mod_ref, 1)
    lang_id = str(mod.get("language", "")).strip()
    if not lang_id:
        die("BLOCKED: lang_project module missing language", 1)
    ext = _get_ext_for_language(lang_id)
    if ext == ".txt" and lang_id not in ("sql", "yaml", "hcl", "mongodb"):
        die("BLOCKED: lang_project cannot determine file extension for " + lang_id, 1)
    snapshot_id = os.environ.get("NLC_DB_SNAPSHOT_ID") or ""
    payload_path = rd / "payload.json"
    if not snapshot_id and payload_path.exists():
        try:
            pl = json.loads(read_text(payload_path))
            snapshot_id = str(pl.get("knowledge_snapshot_id", "")).strip()
        except Exception:
            pass
    if not snapshot_id:
        die("BLOCKED: lang_project requires NLC_DB_SNAPSHOT_ID or payload.knowledge_snapshot_id", 1)
    extract_cfg = mod.get("extract_rules", mod.get("extract", {})) or {}
    extract_cfg = dict(extract_cfg)
    extract_cfg["language"] = lang_id
    extract_cfg["must_contain_any"] = []  # lang_project: filter by lang_hints only, no content filter
    db_path = SNAP_ROOT / snapshot_id / "nlc.db"
    nodes = _kd_extract(db_path, extract_cfg)
    if not nodes:
        die("BLOCKED: lang_project KD extract returned 0 usable nodes for " + lang_id, 1)
    src_dir = workspace_project / "src"
    src_dir.mkdir(parents=True, exist_ok=True)
    run_hint = _lang_run_hint(lang_id, ext.lstrip(".") if ext.startswith(".") else ext)
    readme_content = f"# {lang_id} project\n\nGenerated from {len(nodes)} node(s).\n\n## HOW TO RUN\n\n{run_hint}\n\n"
    write_text(workspace_project / "README.md", readme_content)
    files_written["README.md"] = sha256_bytes(readme_content.encode("utf-8"))
    main_content_parts = []
    use_build_stub = lang_id in ("c", "cpp")
    if use_build_stub:
        main_body = "/* Factory: main */\n#include <stdio.h>\nint main(void) { printf(\"1\\n\"); return 0; }\n" if lang_id == "c" else "/* Factory: main */\n#include <iostream>\nint main() { std::cout << \"1\\n\"; return 0; }\n"
    else:
        for i, (nid, source_url, content) in enumerate(nodes[:3]):
            main_content_parts.append(f"# node:{nid}\n# source: {source_url}\n\n{content}")
        main_body = "\n\n".join(main_content_parts)
    main_file = f"src/main{ext}"
    write_text(workspace_project / main_file, main_body)
    files_written[main_file] = sha256_bytes(main_body.encode("utf-8"))
    lib_stub = "# Factory: second source file\n"
    if ext == ".c":
        lib_stub = "/* Factory: lib */\nint helper(void) { return 1; }\n"
    elif ext in (".cpp", ".cc", ".cxx"):
        lib_stub = "// Factory: lib\nint helper() { return 1; }\n"
    elif ext in (".js", ".mjs"):
        lib_stub = "// Factory: second source file\nmodule.exports = {};\n"
    elif ext == ".go":
        lib_stub = "package main\n\n// Factory: second source file\nfunc helper() bool { return true }\n"
    elif ext == ".rs":
        lib_stub = "// Factory: second source file\n"
    elif ext == ".java":
        lib_stub = "// Factory: second source file\npublic class Lib {}\n"
    elif ext in (".sh", ".bash"):
        lib_stub = "#!/bin/bash\n# Factory: second source file\nhelper() { true; }\n"
    elif ext == ".html":
        lib_stub = "<!-- Factory: second source file -->\n"
    elif ext == ".ts" or ext == ".tsx":
        lib_stub = "// Factory: second source file\nexport {};\n"
    elif ext == ".tf" or ext == ".hcl":
        lib_stub = "# Factory: second source file\n"
    lib_file = f"src/lib{ext}"
    write_text(workspace_project / lib_file, lib_stub)
    files_written[lib_file] = sha256_bytes(lib_stub.encode("utf-8"))
    _emit_manifest_for_language(workspace_project, lang_id, files_written)
    return files_written


def _generate_domain_pack(
    rd: Path,
    workspace_project: Path,
    artifact_class: str,
    mod_ref_prefix: str,
    lang_id: str,
    outputs: list[tuple[str, str]],
    run_hint: str,
    use_defaults_only: bool = False,
) -> dict:
    """KD-backed domain pack: extract nodes, emit domain-correct files. Hard-fail if 0 nodes."""
    files_written = {}
    module_refs = load_module_refs(rd)
    if not module_refs or len(module_refs) != 1 or not str(module_refs[0]).startswith(mod_ref_prefix):
        die(f"BLOCKED: {artifact_class} requires exactly one module_ref ({mod_ref_prefix}...)", 1)
    mod = get_module_by_ref(module_refs[0])
    if not mod:
        die(f"BLOCKED: {artifact_class} module not found", 1)
    snapshot_id = os.environ.get("NLC_DB_SNAPSHOT_ID") or ""
    payload_path = rd / "payload.json"
    if not snapshot_id and payload_path.exists():
        try:
            pl = json.loads(read_text(payload_path))
            snapshot_id = str(pl.get("knowledge_snapshot_id", "")).strip()
        except Exception:
            pass
    if not snapshot_id:
        die(f"BLOCKED: {artifact_class} requires NLC_DB_SNAPSHOT_ID or payload.knowledge_snapshot_id", 1)
    extract_cfg = mod.get("extract_rules", mod.get("extract", {})) or {}
    extract_cfg = dict(extract_cfg)
    extract_cfg["language"] = lang_id
    extract_cfg["must_contain_any"] = []
    db_path = SNAP_ROOT / snapshot_id / "nlc.db"
    nodes = _kd_extract(db_path, extract_cfg)
    if not nodes:
        die(f"BLOCKED: {artifact_class} KD extract returned 0 usable nodes for {lang_id}", 1)
    content_parts = []
    for i, (nid, source_url, content) in enumerate(nodes[:5]):
        content_parts.append(f"# node:{nid}\n# source: {source_url}\n\n{content}")
    kd_body = "\n\n".join(content_parts)
    readme_lines = [f"# {artifact_class} project", "", f"Generated from {len(nodes)} node(s).", "", "## HOW TO RUN", "", run_hint, ""]
    readme_content = "\n".join(readme_lines)
    workspace_project.mkdir(parents=True, exist_ok=True)
    write_text(workspace_project / "README.md", readme_content)
    files_written["README.md"] = sha256_bytes(readme_content.encode("utf-8"))
    for i, (fname, default_content) in enumerate(outputs):
        if fname == "README.md":
            continue
        body = default_content if use_defaults_only else (content_parts[0] if content_parts and i == 0 else default_content)
        if not body or not body.strip():
            body = default_content
        write_text(workspace_project / fname, body)
        files_written[fname] = sha256_bytes(body.encode("utf-8"))
    return files_written


def generate_web_site(rd: Path, tasks: list, workspace_project: Path) -> dict:
    """web_site: index.html, styles.css, app.js, README. Deterministic valid HTML for Tier3."""
    outputs = [
        ("index.html", "<!DOCTYPE html>\n<html><head><link rel=\"stylesheet\" href=\"styles.css\"></head><body><div id=\"app\"></div><script src=\"app.js\"></script></body></html>"),
        ("styles.css", "/* Factory styles */\n#app { padding: 1rem; }\n"),
        ("app.js", "// Factory app\ndocument.getElementById('app').textContent = 'Hello';\n"),
    ]
    return _generate_domain_pack(
        rd, workspace_project, "web_site", "web_site/",
        "html", outputs,
        "Open index.html in a browser (file:// or local server). No network required.",
        use_defaults_only=True,
    )


def generate_sql_pack(rd: Path, tasks: list, workspace_project: Path) -> dict:
    """sql_pack: schema.sql, queries.sql, README with sqlite example. Uses deterministic valid SQL for build check."""
    outputs = [
        ("schema.sql", "-- Schema\nCREATE TABLE IF NOT EXISTS example (id INTEGER PRIMARY KEY, name TEXT);\n"),
        ("queries.sql", "-- Queries\nSELECT * FROM example;\n"),
    ]
    return _generate_domain_pack(
        rd, workspace_project, "sql_pack", "sql_pack/",
        "sql", outputs,
        "sqlite3 example.db < schema.sql && sqlite3 example.db < queries.sql",
        use_defaults_only=True,
    )


def generate_mongo_pack(rd: Path, tasks: list, workspace_project: Path) -> dict:
    """mongo_pack: queries.js, README. Local instructions, no real DB required."""
    outputs = [
        ("queries.js", "// MongoDB shell queries\ndb.example.find({});\n"),
    ]
    return _generate_domain_pack(
        rd, workspace_project, "mongo_pack", "mongo_pack/",
        "mongodb", outputs,
        "Run with mongosh or node. Local: mongosh < queries.js",
    )


def generate_compose_pack(rd: Path, tasks: list, workspace_project: Path) -> dict:
    """compose_pack: docker-compose.yml, README. Validation-only if docker absent."""
    outputs = [
        ("docker-compose.yml", "version: \"3\"\nservices:\n  app:\n    image: alpine\n    command: echo hello\n"),
    ]
    return _generate_domain_pack(
        rd, workspace_project, "compose_pack", "compose_pack/",
        "docker", outputs,
        "docker-compose up (or validate YAML if docker not installed)",
    )


def generate_yaml_pack(rd: Path, tasks: list, workspace_project: Path) -> dict:
    """yaml_pack: config.yaml, example.yaml, README. Deterministic valid YAML for Tier3."""
    outputs = [
        ("config.yaml", "version: 1\nsettings: {}\n"),
        ("example.yaml", "key: value\nlist:\n  - a\n  - b\n"),
    ]
    return _generate_domain_pack(
        rd, workspace_project, "yaml_pack", "yaml_pack/",
        "yaml", outputs,
        "Use with kubectl apply -f or validate with yamllint if available.",
        use_defaults_only=True,
    )


def generate_lang_emit(rd: Path, tasks: list, workspace_project: Path) -> dict:
    """Generate lang_emit project via KD extract (no templates)."""
    files_written = {}
    module_refs = load_module_refs(rd)
    if not module_refs:
        die("lang_emit requires module_refs in payload.json", 1)

    mod = get_module_by_ref(module_refs[0])
    if not mod:
        die(f"lang_emit: module not found: {module_refs[0]}", 1)

    emit = mod.get("emit", {}) or {}
    strategy = str(emit.get("strategy", "")).strip()
    if strategy != "kd_extract":
        die(f"lang_emit: emit.strategy must be 'kd_extract', got '{strategy}'", 1)

    extract_cfg = emit.get("extract", {}) or {}
    lang_id = str(mod.get("language", "") or extract_cfg.get("language", "")).strip()
    if not lang_id:
        die("lang_emit: module missing language", 1)

    snapshot_id = os.environ.get("NLC_DB_SNAPSHOT_ID") or ""
    payload_path = rd / "payload.json"
    if not snapshot_id and payload_path.exists():
        try:
            pl = json.loads(read_text(payload_path))
            snapshot_id = str(pl.get("knowledge_snapshot_id", "")).strip()
        except Exception:
            pass
    if not snapshot_id:
        die("lang_emit: NLC_DB_SNAPSHOT_ID or payload.knowledge_snapshot_id required", 1)

    db_path = SNAP_ROOT / snapshot_id / "nlc.db"
    nodes = _kd_extract(db_path, extract_cfg)
    if not nodes:
        die("lang_emit: kd_extract returned 0 nodes (hard fail for executable intent)", 1)

    ext = _get_ext_for_language(lang_id)
    src_dir = workspace_project / "src"
    src_dir.mkdir(parents=True, exist_ok=True)

    run_hint = _lang_run_hint(lang_id, ext.lstrip(".") if ext.startswith(".") else ext)
    readme_lines = [
        f"# {lang_id} KD-extracted snippets",
        "",
        f"Generated from {len(nodes)} node(s).",
        "",
        "## HOW TO RUN",
        "",
        run_hint,
        "",
    ]
    readme_content = "\n".join(readme_lines) + "\n"
    readme_path = workspace_project / "README.md"
    write_text(readme_path, readme_content)
    files_written["README.md"] = sha256_bytes(readme_content.encode("utf-8"))

    for i, (nid, source_url, content) in enumerate(nodes, 1):
        out_file = f"src/generated_{i}{ext}"
        out_path = workspace_project / out_file
        body = f"# node:{nid}\n# source: {source_url}\n\n{content}"
        write_text(out_path, body)
        files_written[out_file] = sha256_bytes(body.encode("utf-8"))

    # Factory enforcement: ensure >= 2 source files
    if len(nodes) == 1:
        lib_file = f"src/lib{ext}"
        lib_content = "# Factory: second source file for project structure\n"
        if ext in (".js", ".mjs"):
            lib_content = "// Factory: second source file\nmodule.exports = {};\n"
        elif ext == ".go":
            lib_content = "package main\n\n// Factory: second source file\n"
        elif ext == ".rs":
            lib_content = "// Factory: second source file\n"
        elif ext == ".java":
            lib_content = "// Factory: second source file\n"
        elif ext in (".sh", ".bash"):
            lib_content = "#!/bin/bash\n# Factory: second source file\n"
        write_text(workspace_project / lib_file, lib_content)
        files_written[lib_file] = sha256_bytes(lib_content.encode("utf-8"))

    # Emit required manifest
    _emit_manifest_for_language(workspace_project, lang_id, files_written)

    # Emit test file (deterministic stub)
    if ext == ".py":
        (workspace_project / "tests").mkdir(parents=True, exist_ok=True)
        test_content = '"""Factory test stub."""\nimport unittest\n\nclass TestPlaceholder(unittest.TestCase):\n    def test_placeholder(self):\n        self.assertTrue(True)\n'
        write_text(workspace_project / "tests" / "test_generated.py", test_content)
        files_written["tests/test_generated.py"] = sha256_bytes(test_content.encode("utf-8"))

    return files_written


def generate_webview(rd: Path, tasks: list, workspace_project: Path) -> dict:
    """Generate webview project (HTML/CSS/JS)"""
    files_written = {}
    
    # Require REQ.json to check for executable intent
    req_obj = load_req(rd)
    intents = req_obj.get("intents", []) if isinstance(req_obj, dict) else []
    
    # Intent-driven: load module_refs from payload, use only those modules
    # HARD-FAIL: If REQ.json has module_refs (executable intent), payload.json MUST have them
    req_has_module_refs = any(
        isinstance(intent, dict) and intent.get("module_refs")
        for intent in intents
    )
    module_refs = load_module_refs(rd)
    if req_has_module_refs and not module_refs:
        die("Executable intent requires module_refs in payload.json but none found. This is a hard failure for intent-driven execution.", 1)
    
    # Get modules
    if module_refs:
        # Use intent-specific modules
        html_module = {}
        js_fetch_module = {}
        js_dom_module = {}
        css_module = {}
        for mod_ref in module_refs:
            mod = get_module_by_ref(mod_ref)
            if "html" in mod_ref.lower() or mod.get("name") == "html_structure":
                html_module = mod
            elif "fetch" in mod_ref.lower() or mod.get("name") == "fetch_flow":
                js_fetch_module = mod
            elif "dom" in mod_ref.lower() or mod.get("name") == "dom_manipulation":
                js_dom_module = mod
            elif "css" in mod_ref.lower() or "styling" in mod_ref.lower() or mod.get("name") == "dark_mode_styling":
                css_module = mod
        # Fallback to first module if specific not found
        if not html_module and module_refs:
            html_module = get_module_by_ref(module_refs[0])
    if not module_refs:
        die("BLOCKED: webview requires module_refs in payload.json. Evidence insufficient for factory generation.", 1)
    
    # Determine files to create from tasks
    html_files = []
    js_files = []
    css_files = []
    
    for task in tasks:
        touches = task.get("touches", [])
        for touch in touches:
            if touch.endswith('.html'):
                html_files.append(touch)
            elif touch.endswith('.js'):
                js_files.append(touch)
            elif touch.endswith('.css'):
                css_files.append(touch)
    
    # Default files if none specified
    if not html_files:
        html_files = ["index.html", "webview.html"]
    if not js_files:
        js_files = ["webview.js", "main.js"]
    if not css_files:
        css_files = ["webview.css", "style.css"]
    
    # Generate HTML (use first HTML file)
    html_file = html_files[0]
    html_path = workspace_project / html_file
    html_template = html_module.get("template", """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Webview</title>
    <link rel="stylesheet" href="{css_file}">
</head>
<body>
    <div id="app"></div>
    <script src="{js_file}"></script>
</body>
</html>""")
    
    css_file = css_files[0] if css_files else "style.css"
    js_file = js_files[0] if js_files else "main.js"
    html_content = html_template.format(css_file=css_file, js_file=js_file)
    write_text(html_path, html_content)
    files_written[html_file] = sha256_bytes(html_content.encode("utf-8"))
    
    # Generate JavaScript (use first JS file)
    js_file_path = workspace_project / js_file
    fetch_code = js_fetch_module.get("code", """const API_BASE = 'http://localhost:5000';
async function loadRequests() {
    try {
        const response = await fetch(`${API_BASE}/requests`);
        const data = await response.json();""")
    
    dom_code = js_dom_module.get("code", """
        const container = document.getElementById('app') || document.body;
        if (container) {
            if (Array.isArray(data)) {
                container.innerHTML = '<ul>' + data.map(item => 
                    '<li>' + JSON.stringify(item) + '</li>'
                ).join('') + '</ul>';
            } else {
                container.textContent = JSON.stringify(data, null, 2);
            }
        }
    } catch (error) {
        console.error('Error loading requests:', error);
    }
}
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', loadRequests);
} else {
    loadRequests();
}""")
    
    js_content = fetch_code + dom_code
    write_text(js_file_path, js_content)
    files_written[js_file] = sha256_bytes(js_content.encode("utf-8"))
    lib_js_content = "// Factory: second source file\nmodule.exports = {};\n"
    write_text(workspace_project / "lib.js", lib_js_content)
    files_written["lib.js"] = sha256_bytes(lib_js_content.encode("utf-8"))
    pkg_content = '{"name":"app","version":"0.1.0","main":"' + js_file + '"}\n'
    write_text(workspace_project / "package.json", pkg_content)
    files_written["package.json"] = sha256_bytes(pkg_content.encode("utf-8"))
    lock_content = '{"name":"app","version":"0.1.0","lockfileVersion":3,"packages":{"":{"name":"app","version":"0.1.0"}}}\n'
    write_text(workspace_project / "package-lock.json", lock_content)
    files_written["package-lock.json"] = sha256_bytes(lock_content.encode("utf-8"))
    
    # Generate CSS (use first CSS file)
    css_file_path = workspace_project / css_file
    css_content = css_module.get("code", """body {
    background-color: #1e1e1e;
    color: #ffffff;
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 20px;
}
#app {
    max-width: 1200px;
    margin: 0 auto;
}""")
    write_text(css_file_path, css_content)
    files_written[css_file] = sha256_bytes(css_content.encode("utf-8"))
    
    return files_written


def load_req(rd: Path) -> dict:
    """Load REQ.json with structured intents. Validates against req_v1. Returns empty dict if missing."""
    req_path = rd / "REQ.json"
    if not req_path.exists():
        return {}

    try:
        obj = json.loads(read_text(req_path))
        if obj:
            is_valid, err = validate_req(obj)
            if not is_valid:
                die(err)
        return obj
    except Exception as e:
        die(str(e))

def validate_req(req_obj: dict) -> tuple[bool, str]:
    """Basic validation of REQ.json structure. Returns (is_valid, error_msg)."""
    if not req_obj:
        return False, "REQ.json is missing"
    
    if "intents" not in req_obj:
        return False, "REQ.json missing 'intents' field"
    
    intents = req_obj.get("intents", [])

    # PIPELINE_MODE: if multiple intents, generate a single run command.
    pipeline_mode = isinstance(intents, list) and len(intents) > 1
    if not isinstance(intents, list):
        return False, "REQ.json 'intents' must be an array"
    
    if len(intents) == 0:
        return False, "REQ.json 'intents' array is empty"
    
    for i, intent in enumerate(intents):
        if not isinstance(intent, dict):
            return False, f"Intent {i} is not an object"
        if "intent_type" not in intent:
            return False, f"Intent {i} missing 'intent_type'"
        if "params" not in intent:
            return False, f"Intent {i} missing 'params'"
    
    return True, ""

def get_intent_emitter(intent_type: str) -> dict:
    """Load intent emitter from library."""
    emitter_path = MODULES_DIR.parent / "intent_emitters" / f"{intent_type}.json"
    if not emitter_path.exists():
        return {}
    
    try:
        return json.loads(read_text(emitter_path))
    except Exception:
        return {}



def emit_pipeline_handler(intents: list[dict]) -> str:
    """Generate deterministic pipeline handler code for multi-intent REQ.

    Supports chaining for common list/data transforms.
    """
    lines: list[str] = []
    lines.append('    # Pipeline execution (deterministic)')
    lines.append('    import sys, json, csv, re')

    def _get_stage_var(i: int) -> str:
        return f"stage{i}"  # deterministic

    for idx, intent in enumerate(intents):
        it = str(intent.get('intent_type') or '')
        params = intent.get('params') or {}
        outv = _get_stage_var(idx)

        if it == 'stdin_support':
            read_mode = str(params.get('read_mode', 'lines'))
            if read_mode != 'lines':
                # Keep strict: only lines supported in pipeline for now
                lines.append(f"    # BLOCK: unsupported stdin read_mode={read_mode}")
                lines.append('    raise SystemExit(2)')
            else:
                lines.append(f"    {outv} = [line.rstrip('\\n\\r') for line in sys.stdin]")
            continue

        if it == 'read_lines':
            fp = str(params.get('file_path', ''))
            enc = str(params.get('encoding', 'utf-8'))
            lines.append(f"    with open({fp!r}, 'r', encoding={enc!r}) as f:")
            lines.append(f"        {outv} = [ln.rstrip('\\n\\r') for ln in f.readlines()]")
            continue

        if it == 'csv_read':
            fp = str(params.get('file_path', ''))
            has_header = bool(params.get('has_header', True))
            lines.append(f"    with open({fp!r}, 'r', encoding='utf-8') as f:")
            lines.append("        reader = csv.reader(f)")
            lines.append(f"        rows = list(reader)")
            if has_header:
                lines.append(f"    header = rows[0] if rows else []")
                lines.append(f"    {outv} = rows[1:] if rows else []")
            else:
                lines.append(f"    {outv} = rows")
            continue

        # For transforms/sinks, determine input variable
        def _in_var(key: str) -> str:
            v = params.get(key)
            if isinstance(v, str) and v.startswith('stage'):
                return v
            # If literal values are provided (e.g., inline numbers), embed them deterministically.
            if isinstance(v, (list, tuple)):
                return repr(list(v))
            if isinstance(v, (int, float, bool)) or v is None:
                return repr(v)
            # default to previous stage
            if idx == 0:
                return 'None'
            return _get_stage_var(idx-1)

        if it == 'filter_contains':
            inv = _in_var('items')
            substring = str(params.get('substring', ''))
            case_sensitive = bool(params.get('case_sensitive', False))
            if case_sensitive:
                lines.append(f"    {outv} = [x for x in {inv} if {substring!r} in (x if isinstance(x,str) else str(x))]")
            else:
                sub = substring.lower()
                lines.append(f"    {outv} = [x for x in {inv} if {sub!r} in ((x.lower() if isinstance(x,str) else str(x).lower()))]")
            continue

        if it == 'csv_select_columns':
            inv = _in_var('items')
            cols = params.get('columns', [])
            has_header = bool(params.get('has_header', True))
            delim = params.get('delimiter', ',')
            src_path = params.get('source_path')
            lines.append(f"    _cols = {cols!r}")
            lines.append(f"    _has_header = {has_header}")
            lines.append(f"    _delimiter = {delim!r}")
            lines.append(f"    _rows = {inv}")
            lines.append(f"    _out_rows = []")
            lines.append(f"    # validate column type vs header flag")
            lines.append(f"    for _c in _cols:")
            lines.append(f"        if _has_header and isinstance(_c, int):")
            lines.append(f"            sys.stderr.write('ERROR: Column indices not allowed when has_header=true\\n')")
            lines.append(f"            sys.exit(2)")
            lines.append(f"        if (not _has_header) and not isinstance(_c, int):")
            lines.append(f"            sys.stderr.write('ERROR: Column names not allowed when has_header=false\\n')")
            lines.append(f"            sys.exit(2)")
            lines.append(f"    _header = []")
            lines.append(f"    if _has_header:")
            lines.append(f"        if {bool(src_path)}:")
            if src_path:
                lines.append(f"            with open({src_path!r}, 'r', encoding='utf-8') as _f:")
                lines.append(f"                _reader = csv.reader(_f, delimiter=_delimiter)")
                lines.append(f"                _rows_full = list(_reader)")
                lines.append(f"            _header = _rows_full[0] if _rows_full else []")
                lines.append(f"            _rows = _rows_full[1:] if _rows_full else []")
            lines.append(f"        if not _header and _rows:")
            lines.append(f"            # attempt to treat first row of _rows as header if available")
            lines.append(f"            _header = _rows[0]")
            lines.append(f"            _rows = _rows[1:]")
            lines.append(f"        _indices = []")
            lines.append(f"        for _c in _cols:")
            lines.append(f"            if _c not in _header:")
            lines.append(f"                sys.stderr.write('ERROR: Unknown column name\\n')")
            lines.append(f"                sys.exit(2)")
            lines.append(f"            _indices.append(_header.index(_c))")
            lines.append(f"        _out_rows.append([_header[i] for i in _indices])")
            lines.append(f"        for _r in _rows:")
            lines.append(f"            if max(_indices) >= len(_r):")
            lines.append(f"                sys.stderr.write('ERROR: Column index out of range\\n')")
            lines.append(f"                sys.exit(2)")
            lines.append(f"            _out_rows.append([_r[i] for i in _indices])")
            lines.append(f"    else:")
            lines.append(f"        _indices = [int(_c) for _c in _cols]")
            lines.append(f"        for _r in _rows:")
            lines.append(f"            if max(_indices) >= len(_r):")
            lines.append(f"                sys.stderr.write('ERROR: Column index out of range\\n')")
            lines.append(f"                sys.exit(2)")
            lines.append(f"            _out_rows.append([_r[i] for i in _indices])")
            lines.append(f"    {outv} = _out_rows")
            continue

        if it == 'grep_regex':
            inv = _in_var('items')
            pattern = str(params.get('pattern', ''))
            ignore_case = bool(params.get('ignore_case', False))
            lines.append(f"    _flags = re.IGNORECASE if {ignore_case} else 0")
            lines.append(f"    try:")
            lines.append(f"        _re = re.compile(r{pattern!r}, _flags)")
            lines.append(f"    except re.error as e:")
            lines.append(f"        sys.stderr.write(f'ERROR: Invalid regex pattern: {{e}}\\n')")
            lines.append(f"        sys.exit(2)")
            lines.append(f"    {outv} = []")
            lines.append(f"    for _line in {inv}:")
            lines.append(f"        if _re.search(_line):")
            lines.append(f"            {outv}.append(_line)")
            continue

        if it == 'unique':
            inv = _in_var('items')
            preserve = bool(params.get('preserve_order', True))
            if preserve:
                lines.append(f"    _seen = set()")
                lines.append(f"    {outv} = []")
                lines.append(f"    for _x in {inv}:")
                lines.append(f"        if _x in _seen:")
                lines.append(f"            continue")
                lines.append(f"        _seen.add(_x)")
                lines.append(f"        {outv}.append(_x)")
            else:
                lines.append(f"    {outv} = sorted(set({inv}))")
            continue

        if it == 'count_lines':
            inv = _in_var('items')
            lines.append(f"    {outv} = {{'line_count': len(list({inv}))}}")
            continue

        if it == 'json_pretty_print':
            inv = _in_var('items')
            lines.append(f"    _text = '\\n'.join({inv}) if isinstance({inv}, list) else str({inv})")
            lines.append(f"    try:")
            lines.append(f"        _obj = json.loads(_text)")
            lines.append(f"    except Exception as e:")
            lines.append(f"        print(f'Invalid JSON: {{e}}', file=sys.stderr)")
            lines.append(f"        raise SystemExit(2)")
            lines.append(f"    {outv} = json.dumps(_obj, ensure_ascii=False, indent=2)")
            continue

        if it == 'parse_numbers':
            inv = _in_var('items')
            lines.append(f"    {outv} = []")
            lines.append(f"    for _ln in {inv}:")
            lines.append(f"        for _m in re.finditer(r'-?\\d+', str(_ln)):")
            lines.append(f"            {outv}.append(int(_m.group(0)))")
            continue

        if it == 'sort_numbers':
            inv = _in_var('numbers')
            rev = bool(params.get('reverse', False))
            lines.append(f"    {outv} = sorted({inv}, reverse={str(rev)})")
            continue

        if it == 'stats_basic':
            inv = _in_var('numbers')
            stats_list = params.get('stats', ['min','max','avg','count'])
            # Emit deterministic stats dict
            lines.append(f"    _nums = list({inv})")
            lines.append(f"    {outv} = {{}}")
            # guard empties
            lines.append(f"    if 'count' in {stats_list!r}: {outv}['count'] = len(_nums)")
            lines.append(f"    if 'min' in {stats_list!r} and _nums: {outv}['min'] = min(_nums)")
            lines.append(f"    if 'max' in {stats_list!r} and _nums: {outv}['max'] = max(_nums)")
            lines.append(f"    if 'avg' in {stats_list!r} and _nums: {outv}['avg'] = (sum(_nums) / len(_nums))")
            continue
        if it == 'output_format':
            inv = _in_var('data')
            fmt = str(params.get('format', 'text')).lower()
            if fmt == 'json':
                # If data is already a pretty-printed JSON string, emit as-is.
                lines.append(f"    if isinstance({inv}, str):")
                lines.append(f"        _out = {inv} if {inv}.endswith('\\n') else {inv} + '\\n'")
                lines.append(f"        sys.stdout.write(_out)")
                lines.append(f"    else:")
                lines.append(f"        sys.stdout.write(json.dumps({inv}, ensure_ascii=False) + '\\n')")
            elif fmt == 'csv':
                # assume list of rows
                lines.append(f"    writer = csv.writer(sys.stdout, lineterminator='\\n')")
                lines.append(f"    for _row in {inv}:")
                lines.append(f"        writer.writerow(_row if isinstance(_row, (list, tuple)) else [_row])")
            else:
                lines.append(f"    if isinstance({inv}, list):")
                lines.append(f"        for _x in {inv}:")
                lines.append(f"            sys.stdout.write(str(_x) + '\\n')")
                lines.append(f"    else:")
                lines.append(f"        sys.stdout.write(str({inv}) + '\\n')")
            lines.append(f"    {outv} = {inv}")
            continue

        if it == 'write_lines':
            inv = _in_var('lines')
            fp = str(params.get('file_path', ''))
            enc = str(params.get('encoding', 'utf-8'))
            lines.append(f"    with open({fp!r}, 'w', encoding={enc!r}) as f:")
            lines.append(f"        _val = {inv}")
            lines.append(f"        if isinstance(_val, str):")
            lines.append(f"            f.write(_val if _val.endswith('\\n') else _val + '\\n')")
            lines.append(f"        else:")
            lines.append(f"            for _x in _val:")
            lines.append(f"                f.write(str(_x) + '\\n')")
            lines.append(f"    {outv} = {inv}")
            continue

        if it == 'csv_write':
            inv = _in_var('data')
            fp = str(params.get('file_path', ''))
            header = params.get('header', None)
            lines.append(f"    with open({fp!r}, 'w', newline='', encoding='utf-8') as f:")
            lines.append("        writer = csv.writer(f, lineterminator='\\n')")
            if header:
                lines.append(f"        writer.writerow({header})")
            lines.append(f"        for _row in {inv}:")
            lines.append(f"            writer.writerow(_row if isinstance(_row, (list, tuple)) else [_row])")
            lines.append(f"    {outv} = {inv}")
            continue

        # Unsupported stage
        lines.append(f"    # BLOCK: unsupported pipeline intent {it}")
        lines.append('    raise SystemExit(2)')

    # No explicit return in pipeline; command finished.
    return "\n".join(lines)

def emit_code_for_intent(intent: dict) -> tuple[str, str]:
    """Generate code for an intent. Returns (command_name, handler_code)."""
    intent_type = intent.get("intent_type")
    params = intent.get("params", {})
    
    emitter = get_intent_emitter(intent_type)
    if not emitter:
        # Missing emitter - return placeholder that signals error
        return ("", f"    # ERROR: Missing intent emitter for '{intent_type}'")
    
    python_code = emitter.get("python_code", "")
    if not python_code:
        return ("", f"    # ERROR: Emitter '{intent_type}' has no python_code")
    
    # Fill template with params
    try:
        handler_code = python_code.format(**params)
    except KeyError as e:
        handler_code = f"    # ERROR: Missing parameter {e} for intent {intent_type}"
    
    # For CLI, generate command name from intent_type
    command_name = intent_type.replace("_", "-")
    return command_name, handler_code

def generate_python_cli(rd: Path, tasks: list, workspace_project: Path) -> dict:
    """Generate Python CLI project from structured intents (REQ.json)"""
    files_written = {}
    
    # Require REQ.json - refuse prose-only requirements
    req_obj = load_req(rd)
    is_valid, error_msg = validate_req(req_obj)
    if not is_valid:
        # Write NEEDS.json to signal missing/invalid REQ.json
        needs_obj = {
            "needs": [
                {
                    "type": "module",
                    "description": f"REQ.json required but missing/invalid: {error_msg}",
                    "required": "REQ.json with structured intents"
                }
            ]
        }
        needs_path = rd / "NEEDS.json"
        needs_path.write_text(json.dumps(needs_obj, indent=2) + "\n", encoding="utf-8")
        die(f"REQ.json required but {error_msg.lower()}", 1)
    
    intents = req_obj.get("intents", [])

    # PIPELINE_MODE: if multiple intents, generate a single run command.
    pipeline_mode = isinstance(intents, list) and len(intents) > 1
    
    # Intent-driven: load module_refs from payload, use only those modules
    # HARD-FAIL: If REQ.json has module_refs (executable intent), payload.json MUST have them
    req_has_module_refs = any(
        isinstance(intent, dict) and intent.get("module_refs")
        for intent in intents
    )
    module_refs = load_module_refs(rd)
    if req_has_module_refs and not module_refs:
        die("Executable intent requires module_refs in payload.json but none found. This is a hard failure for intent-driven execution.", 1)
    
    # Get parameterized template
    if module_refs:
        # Use intent-specific modules
        argparse_module = {}
        for mod_ref in module_refs:
            mod = get_module_by_ref(mod_ref)
            if mod.get("name") == "argparse_setup" or "argparse" in mod_ref.lower():
                argparse_module = mod
                break
        if not argparse_module:
            argparse_module = get_module_by_ref(module_refs[0]) if module_refs else {}
    if not module_refs:
        die("BLOCKED: python_cli requires module_refs in payload.json. Evidence insufficient for factory generation.", 1)
    template = argparse_module.get("template", """#!/usr/bin/env python3
import argparse

def main():
    parser = argparse.ArgumentParser(description='CLI application')
{COMMAND_DEFINITIONS}
    args = parser.parse_args()
    
{COMMAND_HANDLERS}

if __name__ == "__main__":
    main()
""")

    # Normalize placeholder indentation from module templates
    template = re.sub(r"(?m)^\s*\{COMMAND_DEFINITIONS\}\s*$", "{COMMAND_DEFINITIONS}", template)
    template = re.sub(r"(?m)^\s*\{COMMAND_HANDLERS\}\s*$", "{COMMAND_HANDLERS}", template)

    # Detect placeholder indentation from template (modules may indent placeholders).
    def _placeholder_indent(t: str, token: str, default: str) -> str:
        for ln in t.splitlines():
            m = re.match(rf"^(\s*)\{{{re.escape(token)}\}}\s*$", ln)
            if m:
                return m.group(1)
        return default

    defs_indent = _placeholder_indent(template, "COMMAND_DEFINITIONS", "    ")
    handlers_indent = _placeholder_indent(template, "COMMAND_HANDLERS", "    ")

    # Clamp indentation to 4 spaces for Python blocks (some module templates may over-indent placeholders)
    if "\t" in defs_indent or len(defs_indent) != 4:
        defs_indent = "    "
    if "\t" in handlers_indent or len(handlers_indent) != 4:
        handlers_indent = "    "

    # Generate commands + handlers from intents
    commands: list[str] = []
    handlers: list[tuple[str, str]] = []
    
    for intent in intents:
        intent_type = intent.get("intent_type")
        emitter = get_intent_emitter(intent_type)
        if not emitter:
            die(f"Missing intent emitter for '{intent_type}'. Add emitter to intent_emitters/ or update REQ.json", 1)
        
        command_name, handler_code = emit_code_for_intent(intent)
        if command_name:
            commands.append(command_name)
        if handler_code:
            handlers.append((command_name, handler_code))

    # If pipeline mode, collapse to a single run command
    if pipeline_mode:
        deduped_commands = ["run"]
        commands = ["run"]
        handlers = [("run", emit_pipeline_handler(intents))]

    # De-dupe commands deterministically (preserve first occurrence order)
    seen = set()
    deduped_commands: list[str] = []
    for c in commands:
        if c in seen:
            continue
        seen.add(c)
        deduped_commands.append(c)

    if not deduped_commands:
        die("No valid command definitions generated from intents", 1)

    # One argparse positional for the selected command (avoid duplicate add_argument bugs)
    choices = ", ".join([f'"{c}"' for c in deduped_commands])
    command_definitions_text = f'    parser.add_argument("command", choices=[{choices}], help="Command to run")'

    # Build an if/elif chain for handlers
    handler_lines: list[str] = []
    first = True
    for cmd, code in handlers:
        prefix = "if" if first else "elif"
        first = False
        # NOTE: Template indents the placeholder only on its first line, so we
        # fully indent here to keep block indentation correct.
        handler_lines.append(f'    {prefix} args.command == "{cmd}":')
        indented_handler = "\n".join(("        " + line) if line.strip() else line for line in code.split("\n"))
        handler_lines.append(indented_handler)
    if not handler_lines:
        handler_lines = ["# No handlers generated"]
    command_handlers_text = "\n".join(handler_lines)
    
    argparse_code = template.format(
        COMMAND_DEFINITIONS=command_definitions_text,
        COMMAND_HANDLERS=command_handlers_text
    )
    
    # Determine main file
    main_files = []
    for task in tasks:
        touches = task.get("touches", [])
        for touch in touches:
            if touch.endswith('.py'):
                main_files.append(touch)
    
    if not main_files:
        main_files = ["main.py", "cli.py"]
    
    main_file = main_files[0]
    main_path = workspace_project / main_file
    write_text(main_path, argparse_code)
    files_written[main_file] = sha256_bytes(argparse_code.encode("utf-8"))
    lib_content = '"""Factory: second source file for project structure."""\ndef helper():\n    return True\n'
    write_text(workspace_project / "lib.py", lib_content)
    files_written["lib.py"] = sha256_bytes(lib_content.encode("utf-8"))
    req_content = "# Factory manifest (pinned)\nrequests==2.31.0\n"
    write_text(workspace_project / "requirements.txt", req_content)
    files_written["requirements.txt"] = sha256_bytes(req_content.encode("utf-8"))
    (workspace_project / "tests").mkdir(parents=True, exist_ok=True)
    test_content = '"""Factory test stub."""\nimport unittest\n\nclass TestPlaceholder(unittest.TestCase):\n    def test_placeholder(self):\n        self.assertTrue(True)\n'
    write_text(workspace_project / "tests" / "test_main.py", test_content)
    files_written["tests/test_main.py"] = sha256_bytes(test_content.encode("utf-8"))
    readme_content = "# Python CLI\n\n## Build\n\n```bash\npip install -r requirements.txt\n```\n\n## Run\n\n```bash\npython main.py <command>\n```\n"
    write_text(workspace_project / "README.md", readme_content)
    files_written["README.md"] = sha256_bytes(readme_content.encode("utf-8"))
    return files_written

def generate_python_api(rd: Path, tasks: list, workspace_project: Path) -> dict:
    """Generate Python API project (Flask/FastAPI)"""
    files_written = {}
    
    # Require REQ.json to check for executable intent
    req_obj = load_req(rd)
    intents = req_obj.get("intents", []) if isinstance(req_obj, dict) else []
    
    # Intent-driven: load module_refs from payload, use only those modules
    # HARD-FAIL: If REQ.json has module_refs (executable intent), payload.json MUST have them
    req_has_module_refs = any(
        isinstance(intent, dict) and intent.get("module_refs")
        for intent in intents
    )
    module_refs = load_module_refs(rd)
    if req_has_module_refs and not module_refs:
        die("Executable intent requires module_refs in payload.json but none found. This is a hard failure for intent-driven execution.", 1)
    
    # Get modules
    if module_refs:
        # Use intent-specific modules
        framework_module = {}
        routes_module = {}
        for mod_ref in module_refs:
            mod = get_module_by_ref(mod_ref)
            if "framework" in mod_ref.lower() or mod.get("name") == "framework_setup":
                framework_module = mod
            elif "routes" in mod_ref.lower() or mod.get("name") == "routes":
                routes_module = mod
        # If not found, use first module
        if not framework_module and module_refs:
            framework_module = get_module_by_ref(module_refs[0])
        if not routes_module and module_refs:
            routes_module = get_module_by_ref(module_refs[0])
    if not module_refs:
        die("BLOCKED: python_api requires module_refs in payload.json. Evidence insufficient for factory generation.", 1)
    
    # Determine main file
    main_files = []
    for task in tasks:
        touches = task.get("touches", [])
        for touch in touches:
            if touch.endswith('.py'):
                main_files.append(touch)
    
    if not main_files:
        main_files = ["api.py", "app.py", "main.py"]
    
    main_file = main_files[0]
    main_path = workspace_project / main_file
    
    # Use Flask by default
    framework_code = framework_module.get("code", """from flask import Flask, jsonify

app = Flask(__name__)
""")
    
    routes_code = routes_module.get("code", """
@app.route('/')
def index():
    return jsonify({"status": "ok"})

@app.route('/requests', methods=['GET'])
def get_requests():
    return jsonify([])

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)
""")
    
    api_content = framework_code + routes_code
    write_text(main_path, api_content)
    files_written[main_file] = sha256_bytes(api_content.encode("utf-8"))
    
    # Generate requirements.txt if needed
    reqs_path = workspace_project / "requirements.txt"
    if not reqs_path.exists():
        reqs_content = "flask==3.0.0\n"
        write_text(reqs_path, reqs_content)
        files_written["requirements.txt"] = sha256_bytes(reqs_content.encode("utf-8"))
    
    return files_written

def generate_python_gui(rd: Path, tasks: list, workspace_project: Path) -> dict:
    """Generate Python GUI project (tkinter)"""
    files_written = {}
    
    # Get modules
    window_module = get_module("python_gui", "window_creation")
    
    # Determine main file
    main_files = []
    for task in tasks:
        touches = task.get("touches", [])
        for touch in touches:
            if touch.endswith('.py'):
                main_files.append(touch)
    
    if not main_files:
        main_files = ["gui.py", "main.py"]
    
    main_file = main_files[0]
    main_path = workspace_project / main_file
    
    window_code = window_module.get("code", """import tkinter as tk
from tkinter import ttk

class App:
    def __init__(self, root):
        self.root = root
        self.root.title("GUI Application")
        self.root.geometry("800x600")
        
        # Create widgets
        self.label = ttk.Label(root, text="Hello, World!")
        self.label.pack(pady=20)
        
        self.button = ttk.Button(root, text="Click Me", command=self.on_button_click)
        self.button.pack(pady=10)
    
    def on_button_click(self):
        self.label.config(text="Button clicked!")

if __name__ == "__main__":
    root = tk.Tk()
    app = App(root)
    root.mainloop()
""")
    
    write_text(main_path, window_code)
    files_written[main_file] = sha256_bytes(window_code.encode("utf-8"))
    
    return files_written

def generate_bash_cli(rd: Path, tasks: list, workspace_project: Path) -> dict:
    """Generate Bash CLI script"""
    files_written = {}
    
    # Intent-driven: load module_refs from payload
    module_refs = load_module_refs(rd)
    req_obj = load_req(rd)
    intents = req_obj.get("intents", []) if isinstance(req_obj, dict) else []
    req_has_module_refs = any(isinstance(intent, dict) and intent.get("module_refs") for intent in intents)
    if req_has_module_refs and not module_refs:
        die("Executable intent requires module_refs in payload.json but none found. This is a hard failure for intent-driven execution.", 1)
    
    # Get module
    if not module_refs:
        die("BLOCKED: bash_cli requires module_refs in payload.json. Evidence insufficient for factory generation.", 1)
    script_module = get_module_by_ref(module_refs[0])
    
    template = script_module.get("template", "#!/bin/bash\nset -euo pipefail\n\n{COMMAND_BODY}\n")
    
    # Determine main file
    main_files = []
    for task in tasks:
        touches = task.get("touches", [])
        for touch in touches:
            if touch.endswith('.sh') or touch.endswith('.bash'):
                main_files.append(touch)
    
    if not main_files:
        main_files = ["run.sh", "main.sh"]
    
    main_file = main_files[0]
    (workspace_project / "src").mkdir(parents=True, exist_ok=True)
    main_path = workspace_project / "src" / main_file
    command_body = "# Main command logic\n    echo \"Hello, World!\""
    script_content = template.replace("{COMMAND_BODY}", command_body)
    write_text(main_path, script_content)
    files_written[f"src/{main_file}"] = sha256_bytes(script_content.encode("utf-8"))
    lib_content = "#!/bin/bash\n# Factory: second source file\nhelper() { true; }\n"
    write_text(workspace_project / "src" / "lib.sh", lib_content)
    files_written["src/lib.sh"] = sha256_bytes(lib_content.encode("utf-8"))
    make_content = "run:\n\tbash src/" + main_file + "\n"
    write_text(workspace_project / "Makefile", make_content)
    files_written["Makefile"] = sha256_bytes(make_content.encode("utf-8"))
    readme_content = "# Bash CLI\n\n## Run\n\n```bash\nbash src/" + main_file + "\n```\n"
    write_text(workspace_project / "README.md", readme_content)
    files_written["README.md"] = sha256_bytes(readme_content.encode("utf-8"))
    return files_written

def generate_go_cli(rd: Path, tasks: list, workspace_project: Path) -> dict:
    """Generate Go CLI application"""
    files_written = {}
    
    # Intent-driven: load module_refs from payload
    module_refs = load_module_refs(rd)
    req_obj = load_req(rd)
    intents = req_obj.get("intents", []) if isinstance(req_obj, dict) else []
    req_has_module_refs = any(isinstance(intent, dict) and intent.get("module_refs") for intent in intents)
    if req_has_module_refs and not module_refs:
        die("Executable intent requires module_refs in payload.json but none found. This is a hard failure for intent-driven execution.", 1)
    
    # Get module
    if not module_refs:
        die("BLOCKED: go_cli requires module_refs in payload.json. Evidence insufficient for factory generation.", 1)
    main_module = get_module_by_ref(module_refs[0])
    
    template = main_module.get("template", "package main\n\nimport \"fmt\"\n\nfunc main() {\n    {COMMAND_BODY}\n}\n")
    
    # Determine main file
    main_files = []
    for task in tasks:
        touches = task.get("touches", [])
        for touch in touches:
            if touch.endswith('.go'):
                main_files.append(touch)
    
    if not main_files:
        main_files = ["main.go"]
    
    main_file = main_files[0]
    (workspace_project / "src").mkdir(parents=True, exist_ok=True)
    main_path = workspace_project / "src" / main_file
    command_body = "fmt.Println(\"Hello, World!\")"
    binary_name = "app"
    go_content = template.replace("{COMMAND_BODY}", command_body).replace("{BINARY_NAME}", binary_name)
    write_text(main_path, go_content)
    files_written[f"src/{main_file}"] = sha256_bytes(go_content.encode("utf-8"))
    lib_content = "package main\n\n// Factory: second source file\nfunc helper() bool { return true }\n"
    write_text(workspace_project / "src" / "lib.go", lib_content)
    files_written["src/lib.go"] = sha256_bytes(lib_content.encode("utf-8"))
    go_mod_content = "module app\n\ngo 1.21\n"
    write_text(workspace_project / "go.mod", go_mod_content)
    files_written["go.mod"] = sha256_bytes(go_mod_content.encode("utf-8"))
    write_text(workspace_project / "go.sum", "")
    files_written["go.sum"] = sha256_bytes(b"")
    readme_content = "# Go CLI\n\n## Build\n\n```bash\ngo build -o app ./src\n```\n\n## Run\n\n```bash\n./app\n```\n"
    write_text(workspace_project / "README.md", readme_content)
    files_written["README.md"] = sha256_bytes(readme_content.encode("utf-8"))
    return files_written

def generate_rust_cli(rd: Path, tasks: list, workspace_project: Path) -> dict:
    """Generate Rust CLI application"""
    files_written = {}
    
    # Intent-driven: load module_refs from payload
    module_refs = load_module_refs(rd)
    req_obj = load_req(rd)
    intents = req_obj.get("intents", []) if isinstance(req_obj, dict) else []
    req_has_module_refs = any(isinstance(intent, dict) and intent.get("module_refs") for intent in intents)
    if req_has_module_refs and not module_refs:
        die("Executable intent requires module_refs in payload.json but none found. This is a hard failure for intent-driven execution.", 1)
    
    # Get module
    if not module_refs:
        die("BLOCKED: rust_cli requires module_refs in payload.json. Evidence insufficient for factory generation.", 1)
    main_module = get_module_by_ref(module_refs[0])
    
    template = main_module.get("template", "fn main() {\n    {COMMAND_BODY}\n}\n")
    
    # Create src directory
    src_dir = workspace_project / "src"
    src_dir.mkdir(parents=True, exist_ok=True)
    
    main_file = "src/main.rs"
    main_path = workspace_project / main_file
    
    # Replace placeholders
    command_body = "println!(\"Hello, World!\");"
    rust_content = template.replace("{COMMAND_BODY}", command_body)
    
    write_text(main_path, rust_content)
    files_written[main_file] = sha256_bytes(rust_content.encode("utf-8"))
    lib_content = "// Factory: second source file\n"
    write_text(workspace_project / "src" / "lib.rs", lib_content)
    files_written["src/lib.rs"] = sha256_bytes(lib_content.encode("utf-8"))
    cargo_content = "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n"
    write_text(workspace_project / "Cargo.toml", cargo_content)
    files_written["Cargo.toml"] = sha256_bytes(cargo_content.encode("utf-8"))
    lock_content = '# This file is automatically @generated by Cargo.\nversion = 3\n\n[[package]]\nname = "app"\nversion = "0.1.0"\ndependencies = []\n\n'
    write_text(workspace_project / "Cargo.lock", lock_content)
    files_written["Cargo.lock"] = sha256_bytes(lock_content.encode("utf-8"))
    readme_content = "# Rust CLI\n\n## Build\n\n```bash\ncargo build\n```\n\n## Run\n\n```bash\ncargo run\n```\n"
    write_text(workspace_project / "README.md", readme_content)
    files_written["README.md"] = sha256_bytes(readme_content.encode("utf-8"))
    return files_written

def generate_java_cli(rd: Path, tasks: list, workspace_project: Path) -> dict:
    """Generate Java CLI application"""
    files_written = {}
    
    # Intent-driven: load module_refs from payload
    module_refs = load_module_refs(rd)
    req_obj = load_req(rd)
    intents = req_obj.get("intents", []) if isinstance(req_obj, dict) else []
    req_has_module_refs = any(isinstance(intent, dict) and intent.get("module_refs") for intent in intents)
    if req_has_module_refs and not module_refs:
        die("Executable intent requires module_refs in payload.json but none found. This is a hard failure for intent-driven execution.", 1)
    
    # Get module
    if not module_refs:
        die("BLOCKED: java_cli requires module_refs in payload.json. Evidence insufficient for factory generation.", 1)
    main_module = get_module_by_ref(module_refs[0])
    
    template = main_module.get("template", "public class Main {\n    public static void main(String[] args) {\n        {COMMAND_BODY}\n    }\n}\n")
    
    # Determine main file
    main_files = []
    for task in tasks:
        touches = task.get("touches", [])
        for touch in touches:
            if touch.endswith('.java'):
                main_files.append(touch)
    
    if not main_files:
        main_files = ["Main.java"]
    
    main_file = main_files[0]
    (workspace_project / "src" / "main" / "java").mkdir(parents=True, exist_ok=True)
    main_path = workspace_project / "src" / "main" / "java" / main_file
    command_body = "System.out.println(\"Hello, World!\");"
    java_content = template.replace("{COMMAND_BODY}", command_body)
    write_text(main_path, java_content)
    files_written[f"src/main/java/{main_file}"] = sha256_bytes(java_content.encode("utf-8"))
    lib_content = "// Factory: second source file\npublic class Lib {}\n"
    write_text(workspace_project / "src" / "main" / "java" / "Lib.java", lib_content)
    files_written["src/main/java/Lib.java"] = sha256_bytes(lib_content.encode("utf-8"))
    pom_content = '<?xml version="1.0"?>\n<project><modelVersion>4.0.0</modelVersion><groupId>app</groupId><artifactId>app</artifactId><version>0.1.0</version></project>\n'
    write_text(workspace_project / "pom.xml", pom_content)
    files_written["pom.xml"] = sha256_bytes(pom_content.encode("utf-8"))
    readme_content = "# Java CLI\n\n## Build\n\n```bash\njavac src/main/java/*.java\n```\n\n## Run\n\n```bash\njava -cp src/main/java Main\n```\n"
    write_text(workspace_project / "README.md", readme_content)
    files_written["README.md"] = sha256_bytes(readme_content.encode("utf-8"))
    return files_written

def main():
    if len(sys.argv) != 3:
        die("Usage: run_generator.py <request_id> <request_dir>")
    
    request_id = sys.argv[1]
    request_dir = Path(sys.argv[2])
    
    if not request_dir.exists():
        die(f"Request directory does not exist: {request_dir}")
    
    workspace_project = request_dir / "workspace" / "project"
    workspace_project.mkdir(parents=True, exist_ok=True)
    
    # Load inputs
    artifact_class, artifact_def = load_artifact_class(request_dir)
    tasks = load_tasks(request_dir)
    
    # Generate based on artifact class
    if artifact_class == "webview":
        files_written = generate_webview(request_dir, tasks, workspace_project)
    elif artifact_class == "python_cli":
        files_written = generate_python_cli(request_dir, tasks, workspace_project)
    elif artifact_class == "python_api":
        files_written = generate_python_api(request_dir, tasks, workspace_project)
    elif artifact_class == "python_gui":
        files_written = generate_python_gui(request_dir, tasks, workspace_project)
    elif artifact_class == "bash_cli":
        files_written = generate_bash_cli(request_dir, tasks, workspace_project)
    elif artifact_class == "go_cli":
        files_written = generate_go_cli(request_dir, tasks, workspace_project)
    elif artifact_class == "rust_cli":
        files_written = generate_rust_cli(request_dir, tasks, workspace_project)
    elif artifact_class == "java_cli":
        files_written = generate_java_cli(request_dir, tasks, workspace_project)
    elif artifact_class == "lang_emit":
        files_written = generate_lang_emit(request_dir, tasks, workspace_project)
    elif artifact_class == "lang_patch":
        files_written = generate_lang_patch(request_dir, tasks, workspace_project)
    elif artifact_class == "lang_project":
        files_written = generate_lang_project(request_dir, tasks, workspace_project)
    elif artifact_class == "web_site":
        files_written = generate_web_site(request_dir, tasks, workspace_project)
    elif artifact_class == "sql_pack":
        files_written = generate_sql_pack(request_dir, tasks, workspace_project)
    elif artifact_class == "mongo_pack":
        files_written = generate_mongo_pack(request_dir, tasks, workspace_project)
    elif artifact_class == "compose_pack":
        files_written = generate_compose_pack(request_dir, tasks, workspace_project)
    elif artifact_class == "yaml_pack":
        files_written = generate_yaml_pack(request_dir, tasks, workspace_project)
    else:
        die(f"Unsupported artifact class: {artifact_class}")
    
    # Write generator output summary
    output_path = request_dir / "generator.out.json"
    output_obj = {
        "request_id": request_id,
        "artifact_class": artifact_class,
        "files_written": files_written,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds") + "Z"
    }
    write_text(output_path, json.dumps(output_obj, indent=2))
    
    print(f"GENERATOR: Generated {len(files_written)} files for {artifact_class}")
    sys.exit(0)

if __name__ == "__main__":
    main()
